name: Test docker-build-push

on:
  push:
    paths:
      - '.github/workflows/docker-build-push.yml'
      - '.github/workflows/test-docker-build-push.yml'
      - '.github/test-cases/**'
  workflow_dispatch: {}

jobs:
  case:
    strategy:
      matrix:
        include:
          - case: case-01-valid-setup
            expected: success
    runs-on: ubuntu-latest
    timeout-minutes: 2
    secrets: inherit
    steps:
      - name: Run ${{ matrix.case }}
        run: |
          echo "::notice::Running case ${{ matrix.case }}, expecting ${{ matrix.expected }}"
          echo "expected=${{ matrix.expected }}" >> $GITHUB_OUTPUT
          echo "cases=${{ toJSON(matrix.include.*.case) }}" >> $GITHUB_OUTPUT

      - name: Call reusable workflow
        uses: ./.github/workflows/docker-build-push.yml
        with:
          image_name: ghcr.io/cusk-io/dot-github-test-docker-build-push-${{ matrix.case }}
          test_script: ./.github/test-cases/docker-build-push/${{ matrix.case }}/test.sh
          compose_file: ./.github/test-cases/docker-build-push/${{ matrix.case }}/docker-compose.yml

  teardown:
    needs: [case]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete test images
        env:
          CASES: ${{ toJSON(needs.case.outputs.cases) }}
        run: |
          for case in $(echo "$CASES" | jq -r '.[]'); do
            gh api \
              --method DELETE \
              "https://ghcr.io/v2/cusk-io/dot-github-test-docker-build-push-${case}/" \
              --fail || true
          done